import os
import time
import traceback
import sys
import uuid
from datetime import datetime

# Optional imports for S3
try:
    import boto3
    from botocore.exceptions import BotoCoreError, ClientError
except Exception:
    boto3 = None

# Configuration via environment variables
INTERVAL_SECONDS = int(os.environ.get("BOT_INTERVAL_SECONDS", "300"))
OUTBOX_DIR = os.environ.get("BOT_OUTBOX_DIR", os.path.join(os.path.dirname(__file__), "outbox"))
UPLOAD_METHOD = os.environ.get("BOT_UPLOAD_METHOD", "local").lower()
WEBHOOK_URL = os.environ.get("BOT_WEBHOOK_URL", "")
S3_BUCKET = os.environ.get("BOT_S3_BUCKET", "")
S3_REGION = os.environ.get("BOT_S3_REGION", "")
AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID", "")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY", "")

def ensure_dirs():
    os.makedirs(OUTBOX_DIR, exist_ok=True)
    logs = os.path.join(os.path.dirname(__file__), "logs")
    os.makedirs(logs, exist_ok=True)

def generate_content():
    safe_now = datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
    uid = uuid.uuid4().hex[:8]
    filename = f"content_{safe_now}_{uid}.md"
    path = os.path.join(OUTBOX_DIR, filename)
    content = [
        f"# Generated content",
        f"**timestamp**: {safe_now}",
        "",
        "This is autogenerated content for testing the scheduled uploader.",
        "",
        "## Summary",
        f"- id: {uid}",
        f"- generated_by: run_bot.py",
        ""
    ]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(content))
    return path

def upload_local(path):
    dest_dir = os.path.join(os.path.dirname(path), "uploaded")
    os.makedirs(dest_dir, exist_ok=True)
    dest = os.path.join(dest_dir, os.path.basename(path))
    os.replace(path, dest)
    return {"method":"local","dest":dest}

def upload_http(path):
    import requests
    if not WEBHOOK_URL:
        raise RuntimeError("WEBHOOK_URL not configured")
    with open(path, "rb") as f:
        files = {"file": (os.path.basename(path), f, "text/markdown")}
        resp = requests.post(WEBHOOK_URL, files=files, timeout=30)
    resp.raise_for_status()
    os.remove(path)
    return {"method":"http","status_code":resp.status_code,"url":WEBHOOK_URL}

def upload_s3(path):
    if boto3 is None:
        raise RuntimeError("boto3 not installed")
    if not S3_BUCKET:
        raise RuntimeError("S3_BUCKET not configured")
    session_kwargs = {}
    if AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY:
        session_kwargs["aws_access_key_id"] = AWS_ACCESS_KEY_ID
        session_kwargs["aws_secret_access_key"] = AWS_SECRET_ACCESS_KEY
    s3 = boto3.client("s3", region_name=S3_REGION or None, **session_kwargs)
    key = f"generated/{os.path.basename(path)}"
    s3.upload_file(path, S3_BUCKET, key)
    os.remove(path)
    return {"method":"s3","bucket":S3_BUCKET,"key":key}

def upload(path):
    if UPLOAD_METHOD == "local":
        return upload_local(path)
    if UPLOAD_METHOD == "http":
        return upload_http(path)
    if UPLOAD_METHOD == "s3":
        return upload_s3(path)
    raise RuntimeError(f"Unknown upload method {UPLOAD_METHOD}")

def main_loop():
    print("run_bot.py started content generator", flush=True)
    ensure_dirs()
    while True:
        try:
            path = generate_content()
            print(f"generated {path}", flush=True)
            result = upload(path)
            print(f"uploaded result {result}", flush=True)
        except Exception:
            traceback.print_exc()
        print("heartbeat", time.strftime("%Y-%m-%d %H:%M:%S"), flush=True)
        time.sleep(INTERVAL_SECONDS)

if __name__ == "__main__":
    try:
        main_loop()
    except KeyboardInterrupt:
        print("run_bot.py received KeyboardInterrupt, exiting", flush=True)
    except Exception:
        traceback.print_exc()
        sys.exit(1)
