import os
import azure.cognitiveservices.speech as speechsdk

# Load Azure Speech credentials from environment variables
SPEECH_KEY = os.getenv("AZURE_SPEECH_KEY")
SPEECH_REGION = os.getenv("AZURE_SPEECH_REGION")

if not SPEECH_KEY or not SPEECH_REGION:
    raise RuntimeError("Missing Azure Speech credentials. Set AZURE_SPEECH_KEY and AZURE_SPEECH_REGION.")

# Output path
OUTPUT_PATH = "assets/audio/voiceover.mp3"

def generate_voiceover(text: str):
    """Generate a JennyNeural voiceover and save it to OUTPUT_PATH."""
    speech_config = speechsdk.SpeechConfig(subscription=SPEECH_KEY, region=SPEECH_REGION)

    # Voice + format
    speech_config.speech_synthesis_voice_name = "en-US-JennyNeural"
    speech_config.set_speech_synthesis_output_format(
        speechsdk.SpeechSynthesisOutputFormat.Audio16Khz32KBitRateMonoMp3
    )

    # Create audio output
    audio_config = speechsdk.audio.AudioOutputConfig(filename=OUTPUT_PATH)

    # Synthesizer
    synthesizer = speechsdk.SpeechSynthesizer(
        speech_config=speech_config,
        audio_config=audio_config
    )

    print(f"Generating voiceover → {OUTPUT_PATH}")
    result = synthesizer.speak_text_async(text).get()

    if result.reason == speechsdk.ResultReason.SynthesizingAudioCompleted:
        print("Voiceover generated successfully.")
    else:
        print("Speech synthesis failed.")
        print(result)
        raise RuntimeError("Azure TTS failed.")

if __name__ == "__main__":
    sample_text = "This is a test voiceover generated by JennyNeural."
    generate_voiceover(sample_text)
